### ISSUE TITLE
Please make an extension (or add this feature to an extension) that puts a like/dislike icon on thumbnails of videos when they are liked/disliked.

### ISSUE THREAD

**Issue by SamSmith90** [avi12/youtube-like-dislike-shortcut#20]
### Is your feature request related to a problem? Please describe

We don't know which videos we liked/dislike in YouTube and until we enter them, being able to see this on the thumbnails would be helpful to YouTube users.

### Is it a change to the extension's functionality or to the pop-up settings page?

Extension's functionality

**Comment by avi12** [comment]
I like this feature, gotta investigate how to pull each video's rating
Also, how should I indicate the rate? As simply putting the corresponding icon will cover a bit of the thumbnail, which isn't a great UX either IMHO

**Comment by SamSmith90** [comment]
I mean if I pressed like to a video, show me that I pressed like to it on the thumbnail of it, and if I (myself) pressed dislike to a certain video, show me alone that I pressed dislike to that video, show the user himself if he pressed like to the video and only to him.

**Comment by SamSmith90** [comment]
Yes, put it on a corner of the thumbnail.

**Comment by SamSmith90** [comment]
Going a little out of the thumbnail maybe.

**Comment by SamSmith90** [comment]
The color green or red on a corner of the video with it going out of the square a bit to not hide the thumbnail a lot.

**Comment by SamSmith90** [comment]
with a finger.

**Comment by avi12** [comment]
Please try to edit comments before posting new ones

**Comment by avi12** [comment]
> Yes, put it on a corner of the thumbnail.

I have a better idea
![image](https://user-images.githubusercontent.com/6422804/192599001-2695e3b6-9aed-4d05-81d0-c6d5c00db631.png)

Green will indicate "liked" whereas red will indicate "disliked"

**Comment by avi12** [comment]
I've been thinking about it and I realized that there isn't an elegant way to show it
Consider the following:
You're in `/feed/subscriptions`, you opened a video in a new tab
Suppose you Like that video - when you return to the `/feed/subscriptions` tab, you'd expect to immediately see the video's thumbnail updating to reflect your Like
This goes for every video in your subscriptions that's within the viewport, as well as to related videos in a `/watch`, videos in the search page, etc
At some point, sooner or later, I wouldn't be surprised if the extension will run into a quota issue, because of which the extension won't be able to reflect the videos' ratings as the YouTube server will block the requests to get each video's rating

Suppose that I go smarter about it, e.g. the extension will only update thumbnails as the user [navigates between tabs](https://developer.chrome.com/docs/extensions/reference/tabs/#event-onUpdated) - this means that I have to add a dangerous ["tabs" permission](https://developer.chrome.com/docs/extensions/reference/tabs/#perms), which will result in:
![image](https://user-images.githubusercontent.com/6422804/208245779-987b1dc4-83ff-407f-9a54-c58fd9d11b13.png)

To get around it, I could perhaps put "tabs" as an [optional permission](https://developer.chrome.com/docs/extensions/reference/permissions/), but still, it would require lots of planning & iterations to get it right
